### PR TITLE
Edited README.md

### PR DESCRIPTION
**Pull request by Akash190104**
Fixed a lot of grammatical errors and rephrased a few sentences. @Ramakm Could you please explain the last sentence of line 10? I would love to fix that too.

### CODE REVIEW

**Comment by Ramakm** [comment]
> > Fixed a lot of grammatical errors and rephrased a few sentences. @Ramakm Could you please explain the last sentence of line 10? I would love to fix that too.

**Comment by Ramakm** [comment]
@Akash190104 Thank you for the update. Yeah the changes done by you looks valid. About that 10th line its about books and sites people follow for learning, which sometimes gets updated but people don't follow those updates more often. Its about that. If you are seeing any kind of mistakes fix it. I will review it and merge it after that, if everything will be correct from your end.

**Comment by Akash190104** [comment]
@Ramakm I just want to understand what did the line "However, if the site you want to analyze disappears or exceptions are made when the module no longer supports version upgrades, etc." wanted to convey. I feel it is incomplete. If not, make me understand what it conveys.

**Comment by Akash190104** [comment]
@Ramakm If that sentence looks fine to you, I have nothing more to change and I would request you to merge this PR.

**Comment by Ramakm** [comment]
@Akash190104 Looks fine. No issue. I will update later on as I think that's not required. Will think about it.

Merged!!

**Comment by Akash190104** [comment]
@Ramakm Thank you so much

**Pull request merged**
